src/canvas/canvas.cpp
- Pan viewport by dragging with one finger (existing behaviour)
- Zoom viewport by pinching with two fingers (didn't work before)
- Rotate viewport by rotating with two fingers (didn't work before)
- Touchscreen gestures currently still don't feel "immediate", i.e. like manipulating an actual physical object. In order to achieve this, the touch positions must stay fixed relative to the model during the gestures. In the current implementation, there's some kind of scaling factor dependent on the canvas size. On my machine, a canvas size of 750x750 feels about right; moving a single point will lag behind the actual finger positions on smaller canvasses and leap ahead on larger canvasses. Zooming and rotating also feels the most natural at this canvas size.
- Right now it is not possible to …
=> Canvas: Fix touchscreen navigation

.github/workflows/all.yml, .github/workflows/win32.yml
This updates [actions/checkout](https://github.com/actions/checkout) to v4, it's current version.
Changelog:
> ## v4.1.0
> - Add support for partial checkout filters
>
> ## v4.0.0
> - Support fetching without the --progress option
> - Update to node20
=> update actions/checkout in GitHub Actions workflows to v4

.github/workflows/macos.yml, scripts/build_macos.sh
I noticed that when linking with llvm's libc++, the system's libc++ was still included, probably linked to other libraries that we depend on?
It caused crashes, so I rolled back to using the system's libc++, and "upped" the github action image to macos-13.
We still have to compile using llvm from homebrew, bacause the clang from macos chokes on `std::format` and the "automatic constructor" stuff (not sure what it's called).
However, compiling using homebrew llvm, and linking to macos's libc++ (libSystem?) works, but only on macos 13 and up.
I guess this is the best solution for now.
=> Use system's stdlibc++, use macos v13 github action runner

doc/building.md
``` 
brew install \
python@3 \ <--- Forgot the antislash here
llvm \
eigen \
opencascade \
pkg-config \
gtk4 \
gtkmm4 \
glm \
range-v3 \
mimalloc \
pygobject3 \
librsvg
```
=> Fix typo in MacOS part building.md

.github/workflows/all.yml, .gitignore, flake.lock, flake.nix, meson.build
- Adds support for macOS and non-`x86_64-linux` platforms to the nix flake
- `meson.build` changes to allow building without `brew`
- Hopefully this hasn't broken the build however I don't have a mac with homebrew to test 😅 
- Adds metadata in preparation for submitting a package to nixpkgs
Test with `nix run github:emilytrau/dune3d/flake-macos`
=> Add macOS support to Nix Flake

meson.build, src/action/action.cpp, src/editor/editor.cpp, src/util/key_util.cpp, src/util/key_util.hpp, src/widgets/capture_dialog.cpp
This PR will remap the PC-based keybindings to align with platform conventions on macOS. `Cmd` will be used instead of `Ctrl`, the non-existent `Alt` key will be replaced with (Mac) `Ctrl`, `Backspace` and `Delete` will be swapped. The remapping allows for a platform-independent default keybinding and makes custom keybindings portable between platforms.
Fixes #58.
Supersedes #59 .
- Remap key modifier codes for Cmd (Mac) to Ctrl (PC) and Ctrl (Mac) to Alt (PC) on Mac
- Swap internal key codes for Backspace and Delete on Mac
- Revert the Mac key remapping for display purposes
- Make `key_sequence_item_to_string` use `keyval_to_string` for pretty-printing keys as well
- Using `Option` as a modifier might not work for non-character keys because it is not configured as a valid modifier key.
=> preferences: Remap macOS keys

src/canvas/canvas.cpp
Fixes #57.
On macOS, rendering the pick buffer is subject to antialiasing artifacts, causing the rendered pick indices to be blended instead of just passed through. As a result, placing the mouse over an entity might not actually select it, but a different entity (or none at all) depending on the blended pick index.
This PR will disable multisampling specifically on macOS and therefore ensure that the pick indices will be passed accurately. Note that the lack of MSAA does not appear to degrade rendering quality.
=> Canvas: Disable MSAA on Mac to fix picking issues

.github/workflows/macos.yml
It seems that using the development version of Meson is no longer required as of Meson 1.4.
=> Use stable Meson on macOS

.github/workflows/macos.yml
This PR syncs the package list used for CI builds with the docs.
See the corresponding MR on dune3d-docs repo: https://github.com/dune3d/dune3d-docs/pull/8
=> Sync macOS package list with docs

meson.build
The Open Cascade dependency is effectively required on all platforms, including macOS.
Before this commit, if CMake was missing on macOS, Open Cascade was not found. Although Meson printed a warning, the configuration step completed successfully, leading to a build error later in the process.
=> Make Open Cascade a required dependency on all platforms

src/document/entity/entity.cpp, src/document/entity/entity.hpp, src/editor/selection_editor.cpp
As a newbie it's quite difficult to comprehend what e.g. "Line in workplane 3" means (3 lines or line number 3?).
Therefore change the following:
1. Add a colon between the type name and the amount
2. Use the plural form if there are multiples of the same entity selected. (Don't use plural for constraints as there seem to be no good plural forms)
=> Make text in selection editor easier to understand

meson.build
Use conditional check to preserve backwards compatibility with environments using the old version (such as the macOS Nix build).
See also #49
=> Adjust link args to work with Open Cascade 7.8.1 on macOS

.github/workflows/macos.yml
This appears to be no longer necessary.
See also #49 and https://github.com/Homebrew/homebrew-core/issues/172204.
=> macOS CI: remove "rebuild glibmm" workaround

src/dune3d_application.cpp
On macOS, the logger window can not be closed. Closing it will move it to the center of the screen and make it non-interactive, but it won't disappear.
The active window changed signal gets triggered during closing the log window, which in turn calls `set_transient_for`. Evidently, calling it at this point in time disrupts the window close action and leaves it in an unexpected state.
~~By moving the `set_transient_for` call to `show_log_window`, it is ensured that it never gets called while the log window is being closed.~~
`set_transient_for` will now only be called if the value changes. This ensures that it never happens while the log window is closing.
=> mac: fix closing of log window

scripts/bundle_macos.sh
Fixes #173.
The bundled app is unable to find the local gsettings schema definitions because they haven't been included in the bundle. This leads to a crash when opening the preferences (related to the color picker schema) or when saving a file (related to the file chooser schema).
=> mac: fix missing gsettings schema in bundle

src/canvas/canvas.cpp
Fixes #172.
There seems to be a platform-specific difference in treatment of the MSAA sampling factor. On arm64-based Macs, setting it to `1` works as expected, but it breaks rendering to the pick buffer on Intel-based Macs. Setting it to `0` ensures compatibility with both platforms.
=> mac: fix broken selection on intel platform

src/canvas/canvas.cpp
Fixes #175.
Previously, in the rare event that the canvas `GestureClick` controller received a `signal_cancelled`, it would just do some minor cleanup without resetting/removing the box selection. These changes will ensure that a `signal_cancel` event is treated the same way as `signal_released`.
Note: I haven't been able to trigger `signal_cancelled` reliably - it only seems to happen once every few dozen attempts, so I can not rule out that the changes lead to undesired behavior in one of the other selection modes. I couldn't spot anything problematic from a cursory glance though.
=> canvas: fix box selection release edge case

src/canvas/shaders/face-vertex.glsl, src/canvas/shaders/icon-vertex.glsl
For some reason, `isnan()` was always returning false, even when being passed a NaN. Given that `isnan(x)` is essentially equivalent to testing if `x != x` (additionally suppressing exceptions from signalling NaNs, which we shouldn't run into here), the latter can just be substituted in instead.
Fixes #184.
=> workaround macOS AMD GPU driver bug

src/canvas/canvas.hpp, src/document/entity/entity_workplane.cpp, src/document/entity/entity_workplane.hpp, src/document/group/group_reference.cpp, src/document/group/group_reference.hpp, src/workspace/workspace_view.hpp
By default, all workplanes are sized to 10x10mm which is tiny by any standard - the resulting work volume is three orders of magnitude smaller than the build volume of any entry-level 3D printer, for instance. I can't provide tangible data on determining the "right" value for the new defaults, but intuitively 100x100mm appears to be a reasonable size.
- When creating a new document, change default XY/YZ/ZX workplane sizes to 100x100mm
- Set default size of newly created workplane entities to 100x100mm
- Adjust default zoom level to adapt for larger workplanes
- With the new increased default size, the maximum workplane size is now only one order of magnitude away from the default. I'm wondering if the maximum size should be increased as well? Anecdotal data point: The 3D model of my CNC …
=> increase default workplane size to 100x100mm

.github/workflows/all.yml
The `DeterminateSystems/magic-nix-cache-action` action has been [deprecated](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/) and no longer works. This PR replaces it with the `nix-community/cache-nix-action` action, which is actively maintained. It also replaces the `DeterminateSystems/nix-installer-action` action with the `nixbuild/nix-quick-install-action` action, which is required for the cache action to work. The cache has been configured to restore based on the runner's OS and architecture, so it should work on any runner.
=> Replace magic-nix-cache-action

src/canvas/shaders/face-vertex.glsl, src/canvas/shaders/icon-vertex.glsl
Fixes #216.
This fix should work because either `nan == nan` or `!isnan(nan)` (or both) should evaluate to `false`, even if one of the implementations is broken.
=> mac: fix point and body color rendering on arm64
